#!/bin/sh
python simulated_code.py 0 &
python simulated_code.py 1 &
python simulated_code.py 2 &
python simulated_code.py 3 &
python simulated_code.py 4 &
python simulated_code.py 5 &
python simulated_code.py 6 &
python simulated_code.py 7 &
python simulated_code.py 8 &
python simulated_code.py 9 &
python simulated_code.py 10 &
python simulated_code.py 11 &
python simulated_code.py 12 &
python simulated_code.py 13 &
python simulated_code.py 14 &
python simulated_code.py 15 &
python simulated_code.py 16 &
python simulated_code.py 17 &
python simulated_code.py 18 &
python simulated_code.py 19 &
